# Generated by Django 5.1.1 on 2024-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coconut_tree_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="mockup_task_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userinput",
            name="input_text",
            field=models.CharField(max_length=255),
        ),
    ]
